### ISSUE TITLE
Hugo / blogdown template?

### ISSUE THREAD

**Issue by cboettig** [jmlondon/uswebr#2]
Nice package, and impressed by the modern look in the standards, nice work by 18F!

Don't suppose you have any ambitions for a Hugo template along these lines?  Or maybe 18F can do that too :P

**Comment by jmlondon** [comment]
18F has a [Jekyll theme available](https://github.com/18F/uswds-jekyll). So, maybe that could be a starting point for someone to migrate to Hugo. 

For this package, I'm likely to keep it pretty focussed and just stick with single document Rmarkdown (maybe, one day, expand to more of a typical bookdown).

**Comment by jmlondon** [comment]
probably should have closed this issue a lifetime ago!

I am starting to think about migrating this to Quarto (see #6) and updating to the latest USWDS 3.0 (see #7). Would hopefully be able to implement a website, blog, along with single HTML documents.
